In [21]:
import pandas as pd
import numpy as np
import pickle
import time

from sklearn.linear_model import LogisticRegressionCV, RidgeClassifierCV
from sklearn.ensemble import RandomForestClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

In [22]:
models_to_validate = [
    LogisticRegressionCV,
    RidgeClassifierCV,
    RandomForestClassifier,
    CatBoostClassifier,
    LGBMClassifier,
    XGBClassifier,
    MultinomialNB
]

In [25]:
fitted_models = {}
for model in models_to_validate:
    with open(f'model_best_weights/{model.__name__}.pickle', 'rb') as handle:
        fitted_models[model.__name__] = pickle.load(handle)

/var/folders/cl/r93zvffj0sz_6qfhc44pj6mr0000gn/T/ipykernel_29911/2155067038.py:4: DeprecationWarning: numpy.core.numeric is deprecated and has been renamed to numpy._core.numeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.numeric._frombuffer.
  fitted_models[model.__name__] = pickle.load(handle)
/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator TfidfTransformer from version 1.5.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator TfidfVectorizer from version 1.5.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegressionCV from version 1.5.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator Pipeline from version 1.5.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator LabelBinarizer from version 1.5.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator RidgeClassifierCV from version 1.5.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 1.5.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator RandomForestClassifier from version 1.5.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator LabelEncoder from version 1.5.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator MultinomialNB from version 1.5.2 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [26]:
val_df = pd.read_csv('DataBases/external_testing_dataset.csv')
val_df

                                               message  ...  sentiment_label
0                 Thank you for the amazing attention.  ...         positive
1    I appreciated how you handled the situation. T...  ...         positive
2    I've been reflecting on the service I received...  ...         positive
3    I wanted to thank you for the pleasant service...  ...         positive
4    My experience with this service was completely...  ...         negative
..                                                 ...  ...              ...
995  After experiencing the response from the team,...  ...         negative
996  In today's competitive market, the somewhat me...  ...         negative
997                             Nice work! Five stars!  ...         positive
998  Your team provided somewhat unsatisfactory cus...  ...         negative
999  In today's competitive market, the rather medi...  ...         negative

[1000 rows x 3 columns]

In [27]:
messages = val_df['message']
labels = val_df['sentiment']

In [28]:
def show_report(models, x_test, y_test):
    df = pd.DataFrame()
    for model_name, model in models.items():
        start_time = time.time()
        pred = model.predict(x_test)
        predict_time = time.time() - start_time
        metrics = {
            'precision': precision_score(y_test, pred),
            'recall': recall_score(y_test, pred),
            'f1': f1_score(y_test, pred),
            'roc_auc': roc_auc_score(y_test, pred),
            'predict_time_sec': predict_time}
        df[model_name] = metrics
    return df

In [29]:
rep = show_report(fitted_models, messages, labels)
rep

/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

                  LogisticRegressionCV  ...  MultinomialNB
precision                     0.864119  ...       0.664894
recall                        0.814000  ...       1.000000
f1                            0.838311  ...       0.798722
roc_auc                       0.843000  ...       0.748000
predict_time_sec              0.010976  ...       0.004543

[5 rows x 7 columns]

In [30]:
val_df.drop(['sentiment_label'], axis=1, inplace=True)

In [31]:
for model_name, model in fitted_models.items():
    y_pred = model.predict(messages)
    val_df[f'{model_name}_predict'] = y_pred

    if model_name != 'RidgeClassifierCV':
        score = np.max(model.predict_proba(messages), axis=1)
        val_df[f'{model_name}_proba'] = score

/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/Users/sidorovegor/Desktop/projects/python/misis/MISIS_sentiment_analysis_project/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [35]:
val_df.iloc[:15, :7]

                                              message  ...  RandomForestClassifier_proba
0                Thank you for the amazing attention.  ...                      0.545113
1   I appreciated how you handled the situation. T...  ...                      0.534526
2   I've been reflecting on the service I received...  ...                      0.548868
3   I wanted to thank you for the pleasant service...  ...                      0.546792
4   My experience with this service was completely...  ...                      0.515060
5   I'm writing to express my satisfaction with th...  ...                      0.533400
6   After experiencing the assistance from this se...  ...                      0.529364
7                               I valued the service.  ...                      0.546399
8   Your team provided extremely exceptional assis...  ...                      0.534498
9   I'm writing to express my dissatisfaction with...  ...                      0.533400
10                         Keep up the pleasant work!  ...                      0.539258
11  I found issues with the assistance. Expecting ...  ...                      0.529364
12  I was pleased with how you handled my inquiry....  ...                      0.532607
13              I was pleased with the customer care.  ...                      0.532607
14      Thank you for the superb response. Top marks!  ...                      0.534474

[15 rows x 7 columns]

In [37]:
val_df.shape

(1000, 15)

In [39]:
val_df.iloc[:15, [0, 1, 7, 8, 9, 10, 11, 12]]

                                              message  ...  XGBClassifier_proba
0                Thank you for the amazing attention.  ...             0.995975
1   I appreciated how you handled the situation. T...  ...             0.675691
2   I've been reflecting on the service I received...  ...             0.978581
3   I wanted to thank you for the pleasant service...  ...             0.999630
4   My experience with this service was completely...  ...             0.922366
5   I'm writing to express my satisfaction with th...  ...             0.524194
6   After experiencing the assistance from this se...  ...             0.666021
7                               I valued the service.  ...             0.993551
8   Your team provided extremely exceptional assis...  ...             0.725973
9   I'm writing to express my dissatisfaction with...  ...             0.614232
10                         Keep up the pleasant work!  ...             0.982006
11  I found issues with the assistance. Expecting ...  ...             0.577047
12  I was pleased with how you handled my inquiry....  ...             0.957162
13              I was pleased with the customer care.  ...             0.982482
14      Thank you for the superb response. Top marks!  ...             0.889611

[15 rows x 8 columns]

In [41]:
val_df.iloc[:15, [0, 1, 13, 14]]

                                              message  ...  MultinomialNB_proba
0                Thank you for the amazing attention.  ...             0.827256
1   I appreciated how you handled the situation. T...  ...             0.800366
2   I've been reflecting on the service I received...  ...             0.890984
3   I wanted to thank you for the pleasant service...  ...             0.869301
4   My experience with this service was completely...  ...             0.774382
5   I'm writing to express my satisfaction with th...  ...             0.766629
6   After experiencing the assistance from this se...  ...             0.688724
7                               I valued the service.  ...             0.955140
8   Your team provided extremely exceptional assis...  ...             0.785335
9   I'm writing to express my dissatisfaction with...  ...             0.508358
10                         Keep up the pleasant work!  ...             0.921523
11  I found issues with the assistance. Expecting ...  ...             0.527805
12  I was pleased with how you handled my inquiry....  ...             0.888164
13              I was pleased with the customer care.  ...             0.914222
14      Thank you for the superb response. Top marks!  ...             0.704503

[15 rows x 4 columns]